### ISSUE TITLE
[IMPROVEMENT]

### ISSUE THREAD

**Issue by OttoES** [PhilippvK/tflite_micro_compiler#1]
**What should be improved?**
Instructions to how to use the code in (initial README.md)

**Describe the solution you'd like**
The current instructions for to use this respiratory are not very clear or maybe incorrect.  Pulling the repository is fine. The next part basically instruct you to cd to build and run cmake -DGET_TF_SRC=ON ..
This is fine but please add a warning that this can take very long...
Some variations are discussed after that which does not appear to me as if it is needed?
The next step to actually compile a model is where I think things are unclear.

The instructions says: cd ../tensorflow
No such directory is present after the cmake run above. After some snooping I found the folder in tflite_micro_compiler/cmake/_deps/tf-src/
This an awkward place for the folder and I can only assume that is because that is the default path of the scrip somewhere? 

The next step also fails: ./compiler hello_world.tflite hello_compiled.cpp hello_
I assume that this implies you are still in the tensor-flow folder. Unfortunately there is no executable called ./compiler that I can find? (I also suggest to change the name of the executable compiler because the model compiler can be confused with the c compilers)

Next it would be nice to know how to compile the examples. Which files are compiled, is there a make file?
Last but not least, if you have your own tflite model, how do you build and compile your own model.
**Additional context**
Add any other context or screenshots about the improvement here.
I am also happy to test your suggestions and even update the document.

Having said all that, thanks for the effort, this looks like an awesome idea.

**Comment by PhilippvK** [comment]
@OttoES Thank you for your feedback.

First, I would like to let you know hat this is only a fork of the [original project](https://github.com/cpetig/tflite_micro_compiler) maintained by @cpetig, Andrew Stevens and [tum-ei-eda](https://github.com/tum-ei-eda). This means that I have not invented this, this repository and especially the documentation here is likely to be outdated and your improvement ideas should probably be aplied/posted to the upstream repository instead.

As I am currently using the extending the tflite_micro_compiler project on a daily basis for my mather thesis, I am aware of its problems and the lack of an up to date manual. However I can not work on it as this point in time due to my thesis deadline in a few weeks. Fortuantely I am looking forward to contribute my downstream improvements and fixes (TF2.5 compatibility etc)

The idea to add some graphs and/or tables on the achievable improvements for some popular models in terms of Setup/Inference time as well as ROM/RAM usage is great and I should be able to use some the benchmarks I ran for my master thesis project for this.

**Comment by OttoES** [comment]
Philipp
My apologies, I should have realized that.
Your reply is much appreciated
Regards
Otto
